Sort recent users by time in descending order
NCI-Agency/anet pull request #3225
Opened 2020-10-01 11:17 UTC by oayvazoglusim

This pr contains changes in the admin page, which includes the order of "Recent Users"
 activities in descending order of time

Closes #3223

#### User changes
-

#### Super User changes
-

#### Admin changes
- Admins can now see the recent user activities sorted in descending order

#### System admin changes

- [ ] anet.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [x] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2020-10-06 10:47 UTC, VassilIordanov requested changes

2020-10-06 10:47 UTC, VassilIordanov commented on src/main/java/mil/dds/anet/resources/AdminResource.java
> +    @SuppressWarnings("unchecked")
`@SuppressWarnings` should only be used as last resort

2020-10-06 10:47 UTC, VassilIordanov commented on src/main/java/mil/dds/anet/resources/AdminResource.java
> +      allActivities.put("recentCalls", new LinkedHashSet<HashMap<String, String>>());
can't the case of recentCalls being empty be handled by the stream?

2020-10-06 10:47 UTC, VassilIordanov commented on src/main/java/mil/dds/anet/resources/AdminResource.java
> +        final LinkedHashSet<HashMap<String, String>> recentCallSet = new LinkedHashSet<>();
Consider using the groupingBy collector

2020-10-09 07:34 UTC, cemalettin-simsoft commented on src/main/java/mil/dds/anet/resources/AdminResource.java
> +    // Put sorted users to the list
This comment reads exactly like the code below, to me, an unnecessary comment is more of a distraction rather than useful information/explanation.

2020-10-22 16:54 UTC, VassilIordanov approved these changes

2020-10-22 16:54 UTC, merged