Improve and extend merge for tasks object
NCI-Agency/anet pull request #3229
Opened 2020-10-05 07:48 UTC by cemalettin-simsoft

Added an admin page to merge duplicate tasks. Admins can choose two task objects and can merge these tasks by picking each field as they wish.
### Release notes

Closes #2993 

#### User changes
-

#### Super User changes
-

#### Admin changes
- Added merge tasks link and page

#### System admin changes
-
- [ ] anet.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [X] Described the user behavior in PR body
  - [X] Referenced/updated all related issues
  - [X] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [X] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [X] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2020-12-08 12:05 UTC, MehmetAli-Simsoft requested changes

2020-12-08 12:05 UTC, MehmetAli-Simsoft commented on src/main/java/mil/dds/anet/database/TaskDao.java
> +    getDbHandle()
Comment explaining the update process can be added.

2020-12-11 12:22 UTC, MehmetAli-Simsoft commented
Hii, I got an error like this while testing the UI side. I add the screen measurement of the error and the Coding error log. 
Thank you..

![Kodkısmı](https://user-images.githubusercontent.com/75360653/101903031-b0c10280-3bc4-11eb-8952-c3e10db0a028.PNG)
![ÖnYüzTest](https://user-images.githubusercontent.com/75360653/101903036-b1f22f80-3bc4-11eb-9d1f-723bfaeac6e7.PNG)

2021-02-24 13:23 UTC, midmarch commented
Seems to be blocked by #3147.

2021-04-14 09:57 UTC, gjvoosten commented
Functionality is not needed by the user.

2021-04-14 09:57 UTC, closed without merging