Add selection feature for dynamically selecting location format
NCI-Agency/anet pull request #3256
Opened 2020-10-20 14:57 UTC by cemalettin-simsoft

Users now can change the location format from client side. No need to change it from "anet-dictionary.yml". "locations/form" and "locations/Show" now has a selection input for dynamically changing location format

### Release notes

Closes #3085

#### User changes
- Users can change the location format between "MGRS" and "LAT_LON" from ANET webpage

#### Super User changes
-

#### Admin changes
- Admins don't need to change it from "anet-dictionary.yml"

#### System admin changes
-
- [ ] anet.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [X] Described the user behavior in PR body
  - [X] Referenced/updated all related issues
  - [X] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [X] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [X] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2020-10-20 18:34 UTC, VassilIordanov submitted a review, later dismissed

2020-10-20 18:34 UTC, VassilIordanov commented on anet-dictionary.yml
> -      format: LAT_LON
We still want to specify the default format in the dictionary. I suggest to leave it here and use it as the default.

2020-10-21 06:05 UTC, cemalettin-simsoft commented on anet-dictionary.yml
> -      format: LAT_LON
Hmm, if we are going to set a default there, we should also set all the possible formats as array of strings. Let me commit a poc for that and we can discuss on the implementation

2020-10-22 10:04 UTC, cemalettin-simsoft commented on anet-dictionary.yml
> -      format: LAT_LON
Now that i think about it more, defining array of formats in anet-dictionary.yml is probably useless. So one default format from the dictionary.

2020-10-22 10:07 UTC, cemalettin-simsoft commented on anet-dictionary.yml
> -      format: LAT_LON
Another question: When a user refreshes the webpage, even if he/she selected a format, the defaulFormat will be used. Should we maybe use local storage for keeping the format setting same between refreshes?

2020-10-22 12:32 UTC, VassilIordanov commented on anet-dictionary.yml
> -      format: LAT_LON
> When a user refreshes the webpage
it should come back to the default.
We do not have user-specific settings and we do not want to change anything globally.

Actually the original request was to have the selection of coordinate type be a part of the coordinate widget itself. I think it is cleaner and more clear. Such as:

coordinate: 18SUJ7082315291 [MGRS] 

The last part being a dropdown on how to display the coordinates

2020-10-22 12:48 UTC, VassilIordanov commented on anet-dictionary.yml
> -      format: LAT_LON
I think it is much simpler if it is self-contained in the coordinate widget

2020-10-22 12:49 UTC, cemalettin-simsoft commented on anet-dictionary.yml
> -      format: LAT_LON
Yes, i will include it to the location widget so we don't have to call it from multiple pages

2020-10-25 09:44 UTC, VassilIordanov commented on anet-dictionary.yml
> -      format: LAT_LON
There is still a need for selecting a format for ANET. I suggest to keep the `format` field name

2020-11-18 10:02 UTC, ysf-simsoft requested changes

2020-11-18 11:32 UTC, cemalettin-simsoft commented on client/src/pages/locations/GeoLocation.js
> +  setLocationFormat: PropTypes.func
We are always showing the selection widget, editable or not, submitting or not.

2020-11-18 11:33 UTC, cemalettin-simsoft commented on client/src/pages/locations/GeoLocation.js
> +  setLocationFormat: PropTypes.func
We are always showing the selection widget, editable or not, submitting or not.

2020-11-18 11:54 UTC, ysf-simsoft requested changes

2020-11-18 11:54 UTC, ysf-simsoft commented on client/src/components/SelectLocationFormat.js
> +  margin-left: 1rem;
`margin-left` is set twice. Also I suggest removing `outline` and add `padding: 4px` which creates a better view in both Chrome and Firefox

2020-11-25 11:29 UTC, gjvoosten submitted a review, later dismissed

2020-11-25 11:29 UTC, gjvoosten commented on client/src/models/Location.js
> +  static locationFormat = Settings.fields.location.format // Default
Suggested change:
```
  static LOCATION_FORMATS = {
    LAT_LON: "LAT_LON",
    MGRS: "MGRS"
  }

  static locationFormat =
    Settings.fields.location.format || Location.LOCATION_FORMATS.LAT_LON
```

2020-11-25 11:29 UTC, gjvoosten commented on src/main/resources/anet-schema.yml
> +
Spurious blank line.

2021-04-01 12:48 UTC, anilsonmez-simsoft approved these changes

2021-04-01 12:50 UTC, merged