Enhance person view and make ANET more responsive
NCI-Agency/anet pull request #3330
Opened 2020-12-02 15:59 UTC by cemalettin-simsoft

Person Page made two column layout and the fields order can be changed, and some parts of the ANET made more responsive. 
Closes #3235 

#### User changes
-

#### Super User changes
-

#### Admin changes
- Admins need to select which person fields and in what order they will be shown on the Person page. Order to layout will be two columned like this.
[Avatar] [ N+1]
[    1    ]  [ N+2] 
[    2    ]  [ N+3] 
[    3    ]  [ N+4] 
[     .    ]  [ N+.] 
[    N   ]  [ N+.] 

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [ ] Described the user behavior in PR body
  - [ ] Referenced/updated all related issues
  - [ ] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [ ] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2021-01-13 08:40 UTC, ysf-simsoft requested changes

2021-01-13 08:40 UTC, ysf-simsoft commented on client/src/periodUtils.js
> +    "Invalid width or screen sizes are not continious. width= ",
typo `continious` -> `continuous`

2021-01-13 08:40 UTC, ysf-simsoft commented on client/src/components/Kanban.js
> +      overflowX: "scroll"
I suggest using `auto` instead of `scroll`.

2021-01-13 08:40 UTC, ysf-simsoft commented on anet-dictionary.yml
> +
Redundant blank line.

2021-01-13 08:40 UTC, ysf-simsoft commented on src/main/resources/anet-schema.yml
> +
Redundant blank line.

2021-01-14 11:51 UTC, cemalettin-simsoft commented on client/src/index.css
> +  margin: 0 0 15px !important;
only for `.advanced-search-content`, not this selector right? Because this would select all the form groups in the list of filters

2021-01-22 07:19 UTC, ysf-simsoft approved these changes

2021-01-22 07:19 UTC, ysf-simsoft commented on client/src/pages/people/Show.js
> +      !hasPosition & canAssignPosition ? (
Should be `&&` i guess.

2021-01-22 11:49 UTC, cemalettin-simsoft commented on client/src/pages/people/Show.js
> +      !hasPosition & canAssignPosition ? (
yes

2021-03-29 11:54 UTC, gjvoosten approved these changes

2021-03-30 12:53 UTC, midmarch approved these changes
LGTM

2021-03-30 13:04 UTC, merged