Give admins edit access on periodic assessments
NCI-Agency/anet pull request #3357
Opened 2020-12-13 20:10 UTC by cemalettin-simsoft

Admins should also be able to edit existing periodic assessments. Server side code already allows this (see https://github.com/NCI-Agency/anet/blob/3ea47353f978ee9b4e44b995bb5f5fec76c4d740/src/main/java/mil/dds/anet/resources/NoteResource.java#L92-L99) but it was forgotten to be implemented in the client side.

todo: add client side tests for these cases
Closes #3352 

#### User changes
-

#### Super User changes
-

#### Admin changes
- Admins can edit existing periodic assessments from now on.

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [X] Described the user behavior in PR body
  - [X] Referenced/updated all related issues
  - [X] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [X] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [X] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2020-12-22 12:43 UTC, cemalettin-simsoft commented on src/main/java/mil/dds/anet/resources/NoteResource.java
> +    // Node type is ASSESSMENT
We don't want to change other note types behavior. So i think we should keep this removed part and add assessments checks as an addition like this:

```
    if (isAuthor || isAdmin) {
      return; // just works as previously
    }
    if ( type == assessment ){
      do additional checks...
      return; 
    }
    throw Forbidden;
```

2020-12-22 12:58 UTC, cemalettin-simsoft commented on src/main/java/mil/dds/anet/resources/NoteResource.java
> +          if (!associatedPositions.contains(userPosition)) {
We want to check if person who is being assessed has position in associated positions of current user or vice versa. something like:
```
final Person relatedPerson = personDao.getByUuid(note.getRelatedObjectUuid());
final Position relatedPosition = relatedPerson.loadPosition();
if (userPosition.associatedPositions.contains(relatedPosition))...
```

2020-12-25 11:04 UTC, MehmetAli-Simsoft requested changes

2021-01-06 14:44 UTC, gjvoosten approved these changes

2021-01-07 07:01 UTC, MehmetAli-Simsoft approved these changes

2021-01-07 07:33 UTC, merged