Add similarity feature to avoid duplicate object creation
NCI-Agency/anet pull request #3390
Opened 2021-01-06 14:09 UTC by cemalettin-simsoft

Discuss details

Closes #106

#### User changes
- 

#### Super User changes
- When super users create ANET objects, they will see a list of similar named objects to avoid duplicate creation

#### Admin changes
-

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [ ] Described the user behavior in PR body
  - [ ] Referenced/updated all related issues
  - [ ] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [ ] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2021-03-29 07:40 UTC, gjvoosten requested changes

2021-03-29 07:40 UTC, gjvoosten commented on client/src/pages/people/Form.js
> +                  {values.firstName.length >= 2 && values.lastName.length >= 2 && (
Maybe define a constant instead of hardcoding `2` here?

2021-03-29 07:40 UTC, gjvoosten commented on client/src/pages/locations/Form.js
> +                    values.name.length >= 3 ? (
Maybe define a constant instead of hardcoding `3` here?

2021-03-29 07:40 UTC, gjvoosten commented on client/src/pages/positions/Form.js
> +                    values.name.length >= 3 ? (
Maybe define a constant instead of hardcoding `3` here?

2021-03-30 12:32 UTC, gjvoosten requested changes

2021-03-30 12:52 UTC, anilsonmez-simsoft commented on client/src/pages/locations/Form.js
> +                    !edit && values.name.length >= MIN_CHARS_FOR_DUPLICATES ? (
Then I get a warning. `extraColElem` doesn't like the boolean input and expects an object.

2021-03-30 12:54 UTC, gjvoosten commented on client/src/pages/locations/Form.js
> +                    !edit && values.name.length >= MIN_CHARS_FOR_DUPLICATES ? (
Ah yes, I did too. :nerd_face:
No change needed then.

2021-03-30 12:54 UTC, gjvoosten approved these changes

2021-03-30 12:57 UTC, merged