nci-agency/anet#3394: Remove tag functionality
NCI-Agency/anet pull request #3396
Opened 2021-01-11 01:41 UTC by VassilIordanov

Removes the currently unused tag functionality.

Closes #3394

#### Admin changes
- Admins are no longer able to enable the use of tags in _anet-dictionary.yml_

#### System admin changes
- [x] anet.yml or anet-dictionary.yml needs change
- [x] db needs migration
- [x] documentation has changed
- [x] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [x] Added and/or updated unit tests
  - [x] Added and/or updated e2e tests
  - [x] Added and/or updated data migrations
  - [x] Updated documentation
  - [x] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2021-01-11 08:37 UTC, dspCarlson commented
@VassilIordanov Will a new type of note be added to indicate it's a former tag?

2021-01-11 09:36 UTC, gjvoosten requested changes

2021-01-11 09:36 UTC, gjvoosten commented on src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
> +    qb.addWhereClause("(c_reports.rank IS NOT NULL OR f_reports.rank IS NOT NULL");
You're missing a closing parenthesis at the end of the clause.

2021-01-11 09:52 UTC, gjvoosten requested changes

2021-01-11 09:52 UTC, gjvoosten commented on src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
> +      qb.addSelectClause("ISNULL(c_reports.rank, 0) + ISNULL(f_reports.rank, 0)");
You're missing ` AS search_rank" at the end of the clause.

2021-01-11 09:56 UTC, gjvoosten requested changes

2021-01-11 09:56 UTC, gjvoosten commented on src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
> +      qb.addSelectClause("ISNULL(c_reports.rank, 0) + ISNULL(f_reports.rank, 0)");
You're missing ` AS search_rank` at the end of the clause.

2021-01-11 10:05 UTC, gjvoosten requested changes

2021-01-11 10:05 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/beans/ReportTest.java
> -    final List<Tag> tags = new ArrayList<Tag>();
Also remove the (now unused) imports for `List` and `ArrayList`.

2021-01-11 10:14 UTC, gjvoosten requested changes

2021-01-11 10:14 UTC, gjvoosten commented on src/main/resources/migrations.xml
> +		<dropTable tableName="reportTags" />
I would personally swap the order of these two statements, so first drop the m2m table `reportTags`, then drop `tags`.

2021-01-11 10:21 UTC, gjvoosten requested changes

2021-01-11 10:21 UTC, gjvoosten commented on src/main/java/mil/dds/anet/beans/search/ReportSearchQuery.java
> -  @GraphQLInputField
If I have a saved search containing a Tag filter, I get an error:
```
[2021-01-11 10:18:25.515] WARN mil.dds.anet.resources.GraphQlResource: Errors: [graphql.execution.InputMapDefinesTooManyFieldsException: The variables input contains a field name 'tagUuid' that is not defined for input object type 'ReportSearchQueryInput' ]
```
![Screenshot_2021-01-11 ANET](https://user-images.githubusercontent.com/445238/104168946-1b9d6d80-53ff-11eb-8da7-b3b613fd0af9.png)

2021-01-11 23:19 UTC, VassilIordanov commented on src/main/resources/migrations.xml
> +					tags.uuid,
I think so. I think it is similar to someone editing a tag...

2021-01-11 23:25 UTC, VassilIordanov commented
> @VassilIordanov Will a new type of note be added to indicate it's a former tag?

@dspCarlson - it will be a regular note, saying 
```previously tagged as _tag_name_ - _tag_descrition_....```

2021-01-12 13:04 UTC, gjvoosten submitted a review, later dismissed

2021-01-12 13:04 UTC, gjvoosten commented on src/main/resources/migrations.xml
> +					tags.uuid,
Editing tags is not possible, but editing notes is, so just one person has to edit the note and it will be different for _all_ linked reports…

2021-01-12 13:04 UTC, gjvoosten commented on src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
> +      qb.addSelectClause("ISNULL(c_reports.rank, 0) + ISNULL(f_reports.rank, 0)");
You're still missing ` AS search_rank` at the end of *this* clause.

2021-01-12 13:04 UTC, gjvoosten commented on src/main/java/mil/dds/anet/search/mssql/MssqlReportSearcher.java
> +    qb.addWhereClause("(c_reports.rank IS NOT NULL OR f_reports.rank IS NOT NULL) AS search_rank");
Remove ` AS search_rank` at the end of *this* clause.

2021-02-15 12:16 UTC, cemalettin-simsoft approved these changes

2021-02-24 10:29 UTC, merged