Refactor GraphQL tests
NCI-Agency/anet pull request #3484
Opened 2021-03-11 14:11 UTC by gjvoosten

Use a framework to generate test classes for our GraphQL service.

Closes NCI-Agency/anet#3414

#### User changes
- none

#### Super User changes
- none

#### Admin changes
- none

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [x] graphql schema has changed
  A few parts of the GraphQL schema that were erroneously present have been removed. They were basically non-functional, so there's no real change for any consumer of the GraphQL API.

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [x] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [x] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2021-03-16 12:58 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/resources/PositionResourceTest.java
> -  @Test
Oops, that line shouldn't have been removed… Will fix that.

2021-03-20 00:57 UTC, MehmetAli-Simsoft requested changes
when i run test cases it gives an error (ReportsResourceTest.java ,OrganizationResourceTest.java ). Thank you ..

2021-03-20 00:57 UTC, MehmetAli-Simsoft commented on src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
>      List<Comment> commentsReturned = returned.getComments();
it can be final ..

2021-03-20 00:57 UTC, MehmetAli-Simsoft commented on src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
> +    List<ReportPersonInput> reportPeopleInput =
it can be final..

2021-03-20 00:57 UTC, MehmetAli-Simsoft commented on src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
> +    List<ReportPersonInput> reportPeopleInput =
it can be final..

2021-03-20 00:57 UTC, MehmetAli-Simsoft commented on src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
>      Instant startDate =
it can be final..

2021-03-20 00:57 UTC, MehmetAli-Simsoft commented on src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
>      Instant endDate =
it can be final..

2021-03-20 00:57 UTC, MehmetAli-Simsoft commented on src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
> +    Report updated = elizabethMutationExecutor.updateReport(FIELDS, true, getReportInput(r));
it can be final..

2021-03-20 00:57 UTC, MehmetAli-Simsoft commented on src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
> +    Report submitted = elizabethMutationExecutor.submitReport(FIELDS, r.getUuid());
it can be final..

2021-03-20 00:57 UTC, MehmetAli-Simsoft commented on src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
> +    Report published = adminMutationExecutor.publishReport("", r.getUuid());
it can be final..

2021-03-20 00:57 UTC, MehmetAli-Simsoft commented on src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
> +    Report returned = elizabethMutationExecutor.createReport(FIELDS, rInput);
it can be final..

2021-03-20 00:57 UTC, MehmetAli-Simsoft commented on src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
> +    Report updated =
it can be final..

2021-03-20 00:57 UTC, MehmetAli-Simsoft commented on src/test/java/mil/dds/anet/test/resources/ReportsResourceTest.java
> +    Report approved = getMutationExecutor("bob").approveReport(FIELDS, null, r.getUuid());
it can be final..

2021-03-20 00:57 UTC, MehmetAli-Simsoft commented on src/test/java/mil/dds/anet/test/resources/SavedSearchResourceTest.java
> +    ReportSearchQueryInput query =
it can be final..

2021-03-20 00:57 UTC, MehmetAli-Simsoft commented on src/test/java/mil/dds/anet/test/resources/TaskApprovalTest.java
> +        // Check reports pending approval (without pagination)
Wouldn't it be better to have the comment at the head? I don't know :)

2021-03-22 11:45 UTC, MehmetAli-Simsoft approved these changes

2021-03-24 09:53 UTC, merged