AB#337: Decrease min height of the rows on the calendar
NCI-Agency/anet pull request #3970
Opened 2022-02-28 06:57 UTC by anilsonmez-simsoft

The minimum height of rows is decreased and the maximum number of events displayed per day is decreased.

Closes #337

#### User changes
- Calendar is more compact so that users can can see more of it without using the vertical scroll

#### Super User changes
- None

#### Admin changes
- None

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2022-03-10 15:01 UTC, gjvoosten requested changes

2023-01-10 10:46 UTC, midmarch approved these changes

2023-01-10 14:58 UTC, midmarch commented on client/src/components/Calendar.js
> +    dayMaxEvents={2} // workaround for https://github.com/fullcalendar/fullcalendar/issues/5595
In my opinion not worth it to make it configurable via the dictionary. Let's have this small imrovement merged and let's move on.

2023-01-10 16:20 UTC, gjvoosten commented on src/main/resources/anet-schema.yml
> +    description: Used in the UI to limit the maximum number of events displayed in the calendar
From this text it is unclear to me what a minimum of 0 (zero) actually means; no limit? default limit? no rows at all? As stated in the other thread, leaving out the configuration option is fine for now.

2023-01-11 08:05 UTC, anilsonmez-simsoft commented on client/src/components/Calendar.js
> +    dayMaxEvents={2} // workaround for https://github.com/fullcalendar/fullcalendar/issues/5595
But I've already made it configurable!

2023-01-12 07:40 UTC, gjvoosten approved these changes

2023-01-12 07:40 UTC, merged