Add super user and administrator filters to position search
NCI-Agency/anet pull request #4079
Opened 2022-08-23 08:35 UTC by anilsonmez-simsoft

Super user and administrator options are added to the position type filter in advanced search

Closes AB#502

#### User changes
- Users can search super user and administrator type positions.

#### Super User changes
- None

#### Admin changes
- None

#### System admin changes
- [x] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2022-08-25 13:27 UTC, gjvoosten requested changes

2022-08-25 13:27 UTC, gjvoosten commented on src/main/resources/anet-schema.yml
> +                title: The permision name of this field
Typo: "permission"

2022-08-25 13:27 UTC, gjvoosten commented on src/main/resources/anet-schema.yml
> +                  title: The permision name of this field
Typo: "permission"

2022-08-25 13:27 UTC, gjvoosten commented on src/main/resources/anet-schema.yml
> +                  description: Used in the UI for the type filter of position,
Dangling comma?

2022-08-25 13:27 UTC, gjvoosten commented on src/main/resources/anet-schema.yml
> +                description: Used in the UI for the type filter of position,
Dangling comma?

2022-09-06 12:54 UTC, midmarch approved these changes
Awesome, is was looking for that functionality!

![Screenshot from 2022-09-06 14-46-05](https://user-images.githubusercontent.com/45197818/188639232-b89240ca-fe14-421e-a696-37c9f5864b13.png)

For the user "position type" maybe confusing as it may not have directly have somehting to do with their (primary) position.

Maybe we can renames this to: "User Type" or "Access Level" or "ANET Privileges".

2022-10-06 13:33 UTC, merged