Redesign Security Banner and move logout button to banner
NCI-Agency/anet pull request #4128
Opened 2022-11-03 06:56 UTC by anilsonmez-simsoft

Security banner is separated from the other components on the header and sign out button is moved to the header so that users can logout from the onboarding page.

Closes AB#587

#### User changes
- Security banner has a new look.
- Sign out button is moved to the header

#### Super User changes
- None

#### Admin changes
- None

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2022-11-03 09:52 UTC, gjvoosten requested changes

2022-11-03 09:52 UTC, gjvoosten commented on client/src/components/SecurityBanner.js
> +              <Dropdown.Item href="/api/logout">Sign out</Dropdown.Item>
Try to search for something, then logout, then login again (can even be as another user): search isn't cleared. You probably need to do a `resetPages()` like before?

2022-11-08 13:58 UTC, midmarch requested changes
Better to display the security marking in bold. 

Ideally we need to display Releasability/dissemination limitation in regular script.

In line with AD 070-001 1-23: 

> All NATO information intended for printed form or electronic display shall carry a NATO
information marking at the top and/or bottom of each page, centred. Ownership, classification
and administrative/category markings shall be indicated in full capitals, **in bold**.
Releasability/dissemination limitation markings shall be indicated in title case, regular script,

2022-11-24 14:28 UTC, gjvoosten approved these changes

2022-11-25 12:16 UTC, midmarch approved these changes
LGTM (screenshot is releasable to the public, NU marking is just an example)
![screencapture-localhost-3000-2022-11-25-13_15_01](https://user-images.githubusercontent.com/45197818/203984106-2da41c6d-493b-4dcd-aa45-a40292791049.png)

2022-11-25 12:37 UTC, merged