Initialize ANET database with command-line options
NCI-Agency/anet pull request #4189
Opened 2022-12-12 10:47 UTC by ce-simsoft

Command line arguments are required for Initialization command instead of command prompt.

Closes [AB#666](https://dev.azure.com/ncia-anet/2aa083a5-af3d-44e1-8c7b-6e9e6b124d91/_workitems/edit/666)

#### User changes
- none

#### Super User changes
- none

#### Admin changes
- none

#### System admin changes
When setting up a fresh installation of ANET, the `anet init` command is no longer interactive but takes its settings with command-line options (run `anet init` without options to see how to use it).
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [x] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2023-01-10 09:07 UTC, midmarch submitted a review, later dismissed
To have an additional log configuration is fine, but to a copy of the entire ANET application configuration is a not a good idea.

2023-01-10 09:07 UTC, midmarch commented on init.yml
> +#### developers!
I don't think these comments are applicable to this log file.

I suggest to replace this with the reason why this log configuration file is different.

2023-01-24 13:12 UTC, gjvoosten requested changes

2023-01-24 13:12 UTC, gjvoosten commented on build.gradle
> +		cmdline.addAll(project.args.split("\\s+"))
This won't allow spaces in the argument values; something like:
```
               cmdline.addAll(project.args.split("(?<!\\\\)\\s+").collect { a -> a.replace("\\ ", " ")})
```
would do that.

2023-01-24 13:26 UTC, gjvoosten commented on src/main/java/mil/dds/anet/InitializationCommand.java
>      engine.getAdminDao().saveSetting(classifString);
Extract this into a private method; it's almost the same code 6 times over.

2023-01-25 07:51 UTC, gjvoosten requested changes
This PR seems to be about AB#666; please update the description and the issue link.`

2023-01-25 07:51 UTC, gjvoosten commented on build.gradle
> +//                            --adminFullName ADMIN,\ Arthur --adminDomainName arthur"
In `insertBaseData-psql.sql` he's called *DMIN, Arthur*…

2023-01-26 14:34 UTC, gjvoosten approved these changes

2023-01-26 14:34 UTC, merged