Update to Node.js v18 LTS
NCI-Agency/anet pull request #4246
Opened 2023-02-15 13:50 UTC by gjvoosten

Update to current Node.js LTS release (v18).
This means our wdio tests needed to be rewritten from sync to async.
Updated wdio/webdriverio to v8.

Closes AB#339

#### User changes
- None

#### Super User changes
- None

#### Admin changes
- None

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [x] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2023-02-15 15:44 UTC, midmarch requested changes
What a massive change!

Looks good, there are just a bunch of functions which may do return a promise, but they are async.

2023-02-15 15:44 UTC, midmarch commented on client/tests/webdriver/baseSpecs/advancedSearch.spec.js
> +async function getObjectType(index) {
Does not look async to me

2023-02-15 15:44 UTC, midmarch commented on client/tests/webdriver/pages/createNewPosition.page.js
> +  async getForm() {
not async

2023-02-15 15:44 UTC, midmarch commented on client/tests/webdriver/pages/createNewPosition.page.js
> +  async getPositionNameInput() {
not async

2023-02-15 15:44 UTC, midmarch commented on client/tests/webdriver/pages/createNewPosition.page.js
> +  async getDuplicatesButton() {
not async

2023-02-15 15:44 UTC, midmarch commented on client/tests/webdriver/pages/createNewPosition.page.js
> +  async getModalContent() {
not async

2023-02-16 09:21 UTC, gjvoosten commented
> What a massive change!
> 
> Looks good, there are just a bunch of functions which may do return a promise, but they are async.

These were all added by the codemod, so let's decide to accept them as-is (instead of having to go through each and every one of them to see if they can be removed or not).

2023-02-16 11:08 UTC, merged