Remove "Superusers" from organization detail page
NCI-Agency/anet pull request #4281
Opened 2023-03-08 13:59 UTC by midmarch

Changes:

- Rename label "Administrating positions" to "Assigned Superusers"
- Remove Superuser listing of organisation positions

Closes [AB#793](https://dev.azure.com/ncia-anet/2aa083a5-af3d-44e1-8c7b-6e9e6b124d91/_workitems/edit/793)

#### System admin changes
- [x] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [x] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [x] Added and/or updated unit tests
  - [x] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [x] Updated documentation
  - [x] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2023-03-09 15:40 UTC, gjvoosten requested changes

2023-03-09 15:40 UTC, gjvoosten commented on client/src/components/previews/OrganizationPreview.js
> -  const superUsers = organization.positions.filter(
You _probably_ want to make the same changes to pages/organizations/Show.js…

2023-03-16 13:05 UTC, gjvoosten requested changes

2023-03-16 13:05 UTC, gjvoosten commented on anet-dictionary.yml
> +        label: Assigned Super Users
Please keep `testDictionaries/no-custom-fields.yml` in line with this change.

2023-03-16 13:05 UTC, gjvoosten commented on anet-dictionary.yml
> +        label: Assigned Super Users
Please keep `testDictionaries/no-custom-fields.yml` in line with this change.

2023-03-16 13:05 UTC, gjvoosten commented on client/tests/e2e/permissions.js
> +  // User is super-user, they may edit position of type super user for
If you change "super user" to "super-user", at least be consistent on the rest of this line…

2023-03-16 13:05 UTC, gjvoosten commented on client/src/pages/organizations/Laydown.js
> +        <PositionTable positions={organization.administratingPositions} id="superUserTable"/>
Code is not properly formatted.

2023-03-16 13:05 UTC, gjvoosten commented on client/tests/e2e/permissions.js
> +  t.pass("Jacob should be able to edit his own organization (\"EF 2.2\")")
Lines are not properly formatted.

2023-03-16 13:05 UTC, gjvoosten commented on client/tests/e2e/permissions.js
> +  const element = await t.context.driver.findElement(By.linkText("CIV DMIN, Arthur"))
Line is not properly formatted.

2023-03-20 09:56 UTC, midmarch commented on client/tests/e2e/permissions.js
> +  const $superUserLinks = await t.context.$$("[id=superUserTable] tbody tr td:nth-child(4) span a")
As the existing indentention appeared a bit inconsistent I tried to allign those as well.

2023-03-20 11:10 UTC, gjvoosten requested changes

2023-03-20 11:10 UTC, gjvoosten commented on client/tests/e2e/permissions.js
> +    /^Super-users cannot create .*$/,
You should update the code as well if you change this (see `client/src/pages/people/Form.js`).

2023-03-20 14:21 UTC, gjvoosten approved these changes

2023-03-20 14:21 UTC, merged