AB#902: Prevent creating a duplicate report when uploading attachment
NCI-Agency/anet pull request #4423
Opened 2023-07-25 10:54 UTC by mk-simsoft

…change description goes here…

Closes #

#### User changes
-

#### Superuser changes
-

#### Admin changes
-

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [ ] Described the user behavior in PR body
  - [ ] Referenced/updated all related issues
  - [ ] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [ ] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2023-08-07 09:00 UTC, hyesilAnka commented on client/src/components/Attachment/UploadAttachment.js
> +      save(updateList[i], relatedObjectUuid, true)
Please handle the fault situation. In case of failure, give a message to the user.

2023-08-07 09:30 UTC, hyesilAnka requested changes

2023-08-07 09:30 UTC, hyesilAnka commented on client/src/components/Attachment/UploadAttachment.js
> +    if (!e.target.files[0]) {
You could change code like
`const file = e.target.files[0]
if(!file) {return}`

2023-08-07 09:30 UTC, hyesilAnka commented on src/main/java/mil/dds/anet/resources/AttachmentResource.java
> +    if (!allowedClassifications.containsKey(classificationKey) && classificationKey != null) {
This line should be changed to `if (classificationKey != null && !allowedClassifications.containsKey(classificationKey) )`

2023-08-07 09:30 UTC, hyesilAnka commented on client/tests/webdriver/baseSpecs/showLocation.spec.js
> +    it("We can go to the show page of Attachment", async() => {
Please remove "We"

2023-08-07 09:58 UTC, mk-simsoft commented on client/src/pages/reports/Form.js
> +        if (attachmentAdd) {
Due to the Formik structure, calling setState() in Formik will give an error even if the structure works. Already in the autoSave function, we change the value with setState() and prevent it from running more than once.

2023-08-09 06:55 UTC, gjvoosten requested changes
This PR contains many changes that are unrelated to AB#902; please create a PR that _only_ fixes that issue.

2023-08-09 14:38 UTC, gjvoosten commented
Obsoleted by #4445.

2023-08-09 14:38 UTC, closed without merging