Allow to assess future dates
NCI-Agency/anet pull request #4503
Opened 2023-09-29 11:40 UTC by og-simsoft

ANET now allows selecting future dates to assess which will be quite useful when planning for upcoming dates.

Closes AB#888

#### User changes
- Users were allowed to select past dates only, now they are also able to select future dates.

#### Superuser changes
- None

#### Admin changes
- None

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [ ] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2023-10-03 10:12 UTC, gjvoosten requested changes

2023-10-03 10:12 UTC, gjvoosten commented on client/src/components/assessments/instant/InstantAssessmentResultsTable.js
> +  const periodsConfig = getPeriodsConfig(recurrence, numberOfPeriods, offset)
Unnecessary change, please revert.

2023-10-03 10:12 UTC, gjvoosten commented on client/src/components/assessments/periodic/PeriodicAssessmentResultsTable.js
> +  const periodsConfig = getPeriodsConfig(recurrence, numberOfPeriods, offset)
Unnecessary change, please revert.

2023-10-03 10:12 UTC, gjvoosten commented on client/src/periodUtils.js
> +export const getPeriodsConfig = (recurrence, numberOfPeriods, offset) => {
Unnecessary change, please revert.

2023-10-11 09:25 UTC, gjvoosten requested changes
Needs quite some changes, which I am going to address myself.

2023-10-11 09:25 UTC, gjvoosten commented on anet-dictionary.yml
> +          allowFutureAssesments: true
This prop applies only to periodic assessments, yet you add it to an instant assessment. You also forgot to add it to the test dictionary.

2023-10-11 09:25 UTC, gjvoosten commented on client/src/periodUtils.js
> +      periodDetails.allowNewAssessments = true
In the context of periodic assessments, this should at least check the assessment configuration to see if future assessments are allowed.

2023-10-11 09:25 UTC, gjvoosten commented on client/tests/webdriver/baseSpecs/assessmentsForTasks.spec.js
> +    it("Should allow seeing add button for the assessments in the future", async() => {
The test description should probably also mention the assessment key for which you are testing this.

2023-10-11 09:25 UTC, gjvoosten commented on client/tests/webdriver/baseSpecs/assessmentsForTasks.spec.js
> +        await ShowTask.getFutureAddAssessmentButton("subTaskMonthly", "monthly")
You are testing this against subTaskMonthly, yet you have not set `allowFutureAssessments: true` for that assessment definition.

2023-10-11 09:25 UTC, gjvoosten commented on client/tests/webdriver/pages/showTask.page.js
> +      "tbody tr:last-child td:last-child"
This table cell always exists, so this doesn't really test anything. The selector should include the button, so:
`"tbody tr:last-child td:last-child button"`

2023-10-11 09:25 UTC, gjvoosten commented on src/main/resources/anet-schema.yml
> +        description: allow assesment dates to be in the future in order to be able to plan future.
Misspelling in "assessment".

2023-10-11 10:21 UTC, midmarch approved these changes
LGTM

2023-10-11 10:22 UTC, merged