Upgrade dropwizard to 4.x
NCI-Agency/anet pull request #4692
Opened 2024-03-13 12:43 UTC by gjvoosten

Upgrade to the latest Dropwizard 4.x.
Also upgrade the test framework for testing the GraphQL API to the Spring-based version 2.x.

Closes AB#1062

#### User changes
- None

#### Superuser changes
- None

#### Admin changes
- None

#### System admin changes
- [ ] anet.yml or anet-dictionary.yml needs change
- [ ] db needs migration
- [ ] documentation has changed
- [ ] graphql schema has changed

### Checklist
  - [x] Described the user behavior in PR body
  - [x] Referenced/updated all related issues
  - [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
  - [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
  - [x] Added and/or updated unit tests
  - [ ] Added and/or updated e2e tests
  - [ ] Added and/or updated data migrations
  - [ ] Updated documentation
  - [ ] Resolved all build errors and warnings
  - [ ] Opened debt issues for anything not resolved here

2024-03-13 17:32 UTC, Chessray requested changes

2024-03-14 09:08 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/database/PersonDaoTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
It's so `@BeforeAll` and `@AfterAll`  don't have to be `static`.

2024-03-14 09:10 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/integration/db/FutureEngagementWorkerTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
It's so `@BeforeAll` and `@AfterAll`  don't have to be `static`.

2024-03-14 09:12 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/GraphQLPluginConfiguration.java
> + * This Spring {@link Configuration} class overrides the default Spring Beans 'graphqlEndpoint' and
The comment was mostly copied from the original source (the generator), but I agree it can be improved.

2024-03-14 09:12 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/SpringTestConfig.java
So the Spring beans etc. get initialised for the tests.

2024-03-14 09:15 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/database/PersonDaoTest.java
> +  public void setUpClass() {
While I mostly avoid package-private, the only exception is probably inside tests.
(Note that e.g. SonarLint doesn't complain about this!)

2024-03-14 14:41 UTC, Chessray commented on src/test/java/mil/dds/anet/test/database/PersonDaoTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
That's how I use them normally. `TestInstance.Lifecycle.PER_CLASS` should be an exception to be used only in cases where the regular setup either doesn't work or is significantly slower.

2024-03-14 14:46 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/database/PersonDaoTest.java
> +@TestInstance(TestInstance.Lifecycle.PER_CLASS)
Well, as you can see we need the `dropwizardApp` Spring bean in these test setup methods (or the `AnetObjectEngine` to be initialised, which is done by the `dropwizardApp`), so they can't be static.

2024-03-14 15:48 UTC, Chessray approved these changes

2024-03-18 12:21 UTC, merged