Add NVG SOAP service
NCI-Agency/anet pull request #5030
Opened 2024-12-18 12:45 UTC by gjvoosten

This adds a SOAP service for NVG (NATO Vector Graphics) to ANET. The service is completely self-describing; you can call the endpoint at `/cxf/nvg/20?wsdl` to get the WSDL, then call **GetCapabilities** to get the parameters, and finally call **GetNvg** with the proper parameters to get an NVG response with the selected engagement reports. Note that in order to be able to get results, you need a valid access token supplied to you by an ANET administrator.

Closes AB#814, AB#1223

#### User changes
- None

#### Superuser changes
- None

#### Admin changes
- Admins can create and delete access tokens for external systems needing access to the NVG SOAP service.
- The settings for the ANET site-wide security classification have moved from the admin settings to the dictionary.

#### System admin changes
- [x] application.yml or anet-dictionary.yml needs change
  The dictionary settings for classification have changed from (e.g.):
  ```yaml
  classification:
    label: Security Marking
      choices:
        public: Public
        NU: NATO UNCLASSIFIED
        NU_rel_EU: NATO UNCLASSIFIED Releasable to EU
  ```
  to:
  ```yaml
  confidentialityLabel:
     label: Security Marking
     choices:
      public:
        color: green
        policy: Public
      NU:
        color: green
        policy: NATO
        classification: UNCLASSIFIED
      NU_rel_EU:
        color: green
        policy: NATO
        classification: UNCLASSIFIED
        releasableTo:
          - EU

  siteClassification: NU
  ```
  Note that the `siteClassification` setting needs to refer to one of the keys of the `confidentialityLabel.choices` above it.
- [x] db needs migration
- [ ] documentation has changed
- [x] graphql schema has changed

### Checklist
- [x] described the user behavior in PR body
- [x] referenced/updated all related issues
- [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
- [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
- [ ] added and/or updated unit tests
- [ ] added and/or updated e2e tests
- [ ] added and/or updated data migrations
- [ ] updated documentation
- [ ] resolved all build errors and warnings
- [ ] opened debt issues for anything not resolved here

2025-02-04 15:01 UTC, midmarch requested changes

2025-02-04 15:01 UTC, midmarch commented on client/src/components/Nav.tsx
> +                  Access tokens
```suggestion
                  Web Service Access tokens
```

2025-02-04 15:01 UTC, midmarch commented on insertBaseData-psql.sql
> +  ('2e45aef0-b9de-4818-be95-b0cc2aececfc', 'Sample Access Token', 'A sample access token for the NVG Web Service', 'AaEge0eLJTP25aRAA5jIZxyzvejJBxPk+kAJDpv+5nc=', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
```suggestion
  ('2e45aef0-b9de-4818-be95-b0cc2aececfc', 'Sample Access Token', 'A sample web service access token for the NVG Web Service', 'AaEge0eLJTP25aRAA5jIZxyzvejJBxPk+kAJDpv+5nc=', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP + INTERVAL '10 years');
```

2025-02-05 10:15 UTC, gjvoosten commented on client/src/components/Nav.tsx
> +                  Access tokens
Changed (everywhere else as well).

2025-02-05 10:15 UTC, gjvoosten commented on insertBaseData-psql.sql
> +  ('2e45aef0-b9de-4818-be95-b0cc2aececfc', 'Sample Access Token', 'A sample access token for the NVG Web Service', 'AaEge0eLJTP25aRAA5jIZxyzvejJBxPk+kAJDpv+5nc=', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
Changed (everywhere else as well).

2025-02-06 10:54 UTC, midmarch approved these changes
LGTM

![image](https://github.com/user-attachments/assets/cf96f183-1fbc-4291-be7a-17f544c1aa0e)

2025-02-06 10:59 UTC, merged