MART reports importer
NCI-Agency/anet pull request #5032
Opened 2024-12-18 16:04 UTC by pacodelcastillolopez

Implementation of a MART reports importer and an admin GUI to monitor it.

Closes #AB1011 MART reports importer

#### User changes
- None

#### Superuser changes
- None

#### Admin changes
- Can see a log of the Mart Report importer in a new screen in the Admin area.

#### System admin changes
- [x] application.yml or anet-dictionary.yml needs change
- [x] db needs migration
- [ ] documentation has changed
- [x] graphql schema has changed

### Checklist
- [x] described the user behavior in PR body
- [ ] referenced/updated all related issues
- [x] commits follow a `repo#issue: Title` title format and [these 7 rules](https://chris.beams.io/posts/git-commit/)
- [x] commits have a [clean history](https://epage.github.io/dev/commits/), otherwise PR may be squash-merged
- [x] added and/or updated unit tests
- [x] added and/or updated e2e tests
- [x] added and/or updated data migrations
- [ ] updated documentation
- [x] resolved all build errors and warnings
- [ ] opened debt issues for anything not resolved here

2025-02-13 13:23 UTC, midmarch approved these changes
As discussed, we test in the Azure testbed after merging

2025-02-25 09:03 UTC, gjvoosten requested changes

2025-02-25 09:03 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +import mil.dds.anet.database.*;
No wildcards imports, PLEASE…

2025-02-25 13:45 UTC, gjvoosten commented on src/main/java/mil/dds/anet/database/MartImportedReportDao.java
> +          .bindList("sequences", sequences);
You should always use:
```java
          .bindList(NULL_KEYWORD, "sequences", sequences);
```
to be safe (else `sequences` is not allowed to be empty).
Import:
```java
import static org.jdbi.v3.core.statement.EmptyHandling.NULL_KEYWORD;
```

2025-02-27 15:36 UTC, gjvoosten requested changes

2025-02-27 15:36 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/MartImporterWorker.java
> +  private final IMailReceiver iMailReceiver;
Please rename this field to just `mailReceiver`.

2025-02-27 15:36 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +      anetReport.setClassification("NKU");
This should not be hard-coded. Instead it should come from the report (there's a custom field called `securityMarking` that should contain the correct value). Site admins need to make sure that both sides have this marking in their configuration.

2025-02-27 15:36 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartTransmissionLogImporterService.java
> +import mil.dds.anet.database.*;
No wildcard imports please…

2025-02-27 15:36 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/TestData.java
> +import java.util.*;
No wildcard imports please…

2025-02-27 15:36 UTC, gjvoosten commented on src/main/java/mil/dds/anet/database/MartImportedReportDao.java
> +
Spurious blank line.

2025-03-12 07:48 UTC, gjvoosten requested changes

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +  private static final String SECURITY_MARKING_JSON_PROPERTY = "securityMarking";
Please move this down below `public static final String REPORT_JSON_ATTACHMENT`.

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +      JsonNode jsonNode = ignoringMapper.readTree(martReport.getCustomFields());
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +      JsonNode securityMarkingProperty = jsonNode.get(SECURITY_MARKING_JSON_PROPERTY);
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +        String martReportClassification = securityMarkingProperty.asText();
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +          anetReporClassification = martReportClassification;
Why not simply:
```java
          return martReportClassification;
```
?

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +
Unnecessary blank line.

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +      Person person = new Person();
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +      Position position = new Position();
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +
Spurious blank line.

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartTransmissionLogImporterService.java
> +      List<LogDto> transmissionLog = ignoringMapper.readValue(
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartTransmissionLogImporterService.java
> +      AnetBeanList<MartImportedReport> existingMartImportedReports = martImportedReportDao
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartTransmissionLogImporterService.java
> +        List<Long> presentSequences = existingMartImportedReports.getList().stream()
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartTransmissionLogImporterService.java
> +        List<LogDto> missing = transmissionLog.stream()
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartTransmissionLogImporterService.java
> +        for (LogDto logDto : missing) {
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartTransmissionLogImporterService.java
> +          MartImportedReport martImportedReport = new MartImportedReport();
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/TestData.java
> +      LogDto logDto = new LogDto();
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/TestData.java
> +    List<LogDto> transmissionLog = new ArrayList<>();
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/TestData.java
> +    LogDto missing1 = new LogDto();
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/TestData.java
> +    LogDto missing2 = new LogDto();
Could be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/integration/mart/MartReportImporterWorkerTest.java
> +    EmailMessage emailMessage9 =
Could all be `final`.

2025-03-12 07:48 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/integration/mart/MartReportImporterWorkerTest.java
> +
Too many blank lines.

2025-03-12 07:48 UTC, gjvoosten commented on src/test/java/mil/dds/anet/test/integration/mart/MartReportImporterWorkerTest.java
> +    IMailReceiver mailReceiverMock = Mockito.mock();
Could be `final`.

2025-03-12 07:49 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/MartImporterWorker.java
> +      IMartTransmissionLogImporterService martTrasmissionLogImporter) {
Please rename to `transmissionLogImporter` (original parameter had a typo as well).

2025-03-12 07:52 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +    if (martReportAttachmentOpt.isPresent()) {
Why not do an early return here:
```java
    // Do we have a MART report in this email?
    if (!martReportAttachmentOpt.isPresent()) {
      return;
    }
```
Makes the method more readable IMHO.

2025-03-12 07:54 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +            getReportInfo(new String(martReportAttachment.getContent(), StandardCharsets.UTF_8));
Variable scopes can be reduced:
```java
      // Get the report JSON from the attachment
      try {
        final FileAttachment martReportAttachment = martReportAttachmentOpt.get();
        martReportAttachment.load();
        final ReportDto reportDto =
            getReportInfo(new String(martReportAttachment.getContent(), StandardCharsets.UTF_8));
```

2025-03-12 07:55 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +        MartImportedReport newMartImportedReport = new MartImportedReport();
Cold be `final`.

2025-03-12 07:55 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +        MartImportedReport existingMartImportedReport =
Cold be `final`.

2025-03-12 07:58 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +        if (existingMartImportedReport != null) {
Suggest to rewrite this `if` to avoid the "dangling else":
```java
        if (existingMartImportedReport == null) {
          // New report, import
          processReportInfo(reportDto, newMartImportedReport, attachments);
          martImportedReportDao.insert(newMartImportedReport);
        } else if (existingMartImportedReport.isSuccess()) {
          // If it was successfully imported it is a duplicate, do not import again
          […]
        } else if (!existingMartImportedReport.isSuccess() && Objects.equals(
            existingMartImportedReport.getSequence(), newMartImportedReport.getSequence())) {
          // This report was marked as failed or missing earlier, import now and replace the
          // existing martImportedReport
          […]
        }
```

2025-03-12 08:06 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +
Spurious blank line.

2025-03-12 08:08 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +    if (matchingPersons.isEmpty()) {
You could reverse the sense of this if and avoid the "dangling else":
```java
    if (!matchingPersons.isEmpty()) {
      // Put everybody with this email as report attendee
      matchingPersons.forEach(person -> reportPeople.add(createReportPerson(person)));
    } else {
      // This is a new person -> CREATE from MART
      […]
    }
```

2025-03-12 08:10 UTC, gjvoosten commented on src/main/java/mil/dds/anet/threads/mart/services/MartReportImporterService.java
> +      if (securityMarkingProperty != null) {
You could reverse the sense of this if and avoid the "dangling else":
```java
      if (securityMarkingProperty == null) {
        errors.add("Security marking is missing");
      } else {
        final String martReportClassification = securityMarkingProperty.asText();
        […]
      }
```

2025-03-24 12:36 UTC, closed without merging